/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day1 {


    int elfTotal = 0;
    List<Integer> elves = new ArrayList<>();

    @Test
    void test() {
        assertEquals(24000, run("day1-test.txt"));
    }

    @Test
    void test2() {
        assertEquals(45000, part2("day1-test.txt"));
    }

    @Test
    void real() {
        run("day1.txt");
    }

    @Test
    void real2() {
        part2("day1.txt");
    }


    private int run(String filename) {
        MessageUtils.readLines(filename, line -> {
                            if (line.isEmpty()) {
                                elves.add(elfTotal);
                                elfTotal = 0;
                            } else {
                                elfTotal += Integer.parseInt(line);
                            }
                            //System.out.println("L: " + line);

        });
        elves.add(elfTotal);
        //elves.forEach(e -> System.out.println("ET: " + e));
        int max = elves.stream().mapToInt(x -> x).max().orElseThrow();
        System.out.println("MAX: " + max);
        return max;
    }

    private int part2(String filename) {
        run(filename);
        int sum = elves.stream()
                .sorted((x, y) -> y-x)
                .mapToInt(x -> x)
                //.sorted()
                .limit(3)
                .sum();
     System.out.println("Sum 3: " + sum);
     return sum;
    }
}
