/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day2 {
    enum Types {
        Schaar,
        Steen,
        Papier;
    }
    enum Result {
        WIN,
        LOSE,
        DRAW;
    }
    private int total = 0;

    @Test
    void test() {
        assertEquals(15, run("day2-test.txt"));
    }

    @Test
    void test2() {
        assertEquals(12, run2("day2-test.txt"));
    }

    @Test
    void real() {
        run("day2.txt");
    }

    @Test
    void real2() {
        run2("day2.txt");
    }

    private int run2(String filename) {

        MessageUtils.readLines(filename, line -> {
            //System.out.println("L: " + line);
            String[] split = line.split(" ");
            if (split.length != 2) {
                throw new RuntimeException("invalid size: " + line);
            }
            Types opponent = switch (split[0]) {
                case "A" -> Types.Steen;
                case "B" -> Types.Papier;
                case "C" -> Types.Schaar;
                default -> throw new RuntimeException("unknown" + line);
            };
//            Result result = switch (split[1]) {
//                case "X" -> Result.LOSE;
//                case "Y" -> Result.DRAW;
//                case "Z" -> Result.WIN;
//                default -> throw new RuntimeException("unknown" + line);
//            };
            Types you = switch (split[1]) {
                case "X" -> //lose
                        switch (opponent) {
                            case Schaar -> Types.Papier;
                            case Steen -> Types.Schaar;
                            case Papier -> Types.Steen;
                        };
                case "Y" -> opponent; //draw
                case "Z" -> //Win
                     switch (opponent) {
                    case Schaar -> Types.Steen;
                    case Steen -> Types.Papier;
                    case Papier -> Types.Schaar;
                };
                default -> throw new RuntimeException("unknown" + line);
            };
            //System.out.println(opponent + " -- " + you);

            int points = switch (you) {
                case Steen -> 1 + switch (opponent) {
                    case Schaar -> 6;
                    case Steen -> 3;
                    case Papier -> 0;
                };
                case Papier -> 2+switch (opponent) {
                    case Schaar -> 0;
                    case Steen -> 6;
                    case Papier -> 3;
                };
                case Schaar -> 3+switch (opponent) {
                    case Schaar -> 3;
                    case Steen -> 0;
                    case Papier -> 6;
                };
            };
            //System.out.println("P: " + points);
            total += points;
        });
        System.out.println("Total: " + total);
        return total;
    }

    private int run(String filename) {

        MessageUtils.readLines(filename, line -> {
            //System.out.println("L: " + line);
            String[] split = line.split(" ");
            if (split.length != 2) {
                throw new RuntimeException("invalid size: " + line);
            }
            Types opponent = switch (split[0]) {
                case "A" -> Types.Steen;
                case "B" -> Types.Papier;
                case "C" -> Types.Schaar;
                default -> throw new RuntimeException("unknown" + line);
            };
            Types you = switch (split[1]) {
                case "X" -> Types.Steen;
                case "Y" -> Types.Papier;
                case "Z" -> Types.Schaar;
                default -> throw new RuntimeException("unknown" + line);
            };
            //System.out.println(opponent + " -- " + you);

            int points = switch (you) {
                case Steen -> 1 + switch (opponent) {
                    case Schaar -> 6;
                    case Steen -> 3;
                    case Papier -> 0;
                };
                case Papier -> 2+switch (opponent) {
                    case Schaar -> 0;
                    case Steen -> 6;
                    case Papier -> 3;
                };
                case Schaar -> 3+switch (opponent) {
                    case Schaar -> 3;
                    case Steen -> 0;
                    case Papier -> 6;
                };
            };
            //System.out.println("P: " + points);
            total += points;
        });
        System.out.println("Total: " + total);
        return total;
    }
}
