/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.invoke.MethodHandles;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day3 {
    private static final Logger LOG = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
    private int sum;
    private char found = '\0';

    @BeforeEach
     void setup() {
        sum = 0;
    }

    @Test
    void test() {
        assertEquals(15, run("day3-test.txt"));
    }

    @Test
    void part1() {
        run("day3.txt");
    }

    private int run(String filename) {
        MessageUtils.readLines(filename, line -> {
            found = '\0';
            int size = line.length();
            if (size % 2 != 0) {
                throw new IllegalStateException("not even");
            }
            String part1 = line.substring(0, size / 2);
            String part2 = line.substring(size / 2, size);
            assertEquals(part1.length(), part2.length());
            for (char c : part1.toCharArray()) {
                if (part2.contains(String.valueOf(c))) {
                    if (found != c && found != '\0') {
                        throw new IllegalStateException("already found: " + c + " -- " + part1 + " -- " + part2);
                    }
                    found = c;
                }
            }
            if (found == '\0') {
                throw new IllegalStateException("not found");
            }
            int foundInt = (int)found;
            int score;
            if (foundInt >= 97) {
                score = foundInt - 97 + 1;
            } else {
                score = foundInt - 65 + 27;
            }
            //LOG.info("Found {} -- {} -- {}", found, (int) found, score);
            sum += score;
        });
        LOG.info("Sum: {}", sum);
        return sum;
    }

}
