/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day1Test {


    @Test
    void test() {
        assertEquals(21, Day1.process(20, "R1"));
        assertEquals(0, Day1.process(52, "R48"));
        assertEquals(95, Day1.process(0, "L5"));
        assertEquals(0, Day1.process(55, "L55"));
    }

    @Test
    void test2() {
        Day1 day1 = new Day1("day1Test.txt");
        day1.run();
        assertEquals(3, day1.getCount0());
    }

    @Test
    void real() {
        Day1 day1 = new Day1("day1.txt");
        day1.run();
        assertEquals(1059, day1.getCount0());
    }

    @Test
    void testP2() {
        assertEquals(new Day1P2.Result(21,0), Day1P2.process(20, "R1"));
        assertEquals(new Day1P2.Result(0,0), Day1P2.process(52, "R48"));
        assertEquals(new Day1P2.Result(95,0), Day1P2.process(0, "L5"));
        assertEquals(new Day1P2.Result(0,0), Day1P2.process(55, "L55"));
        assertEquals(new Day1P2.Result(55,3), Day1P2.process(55, "R300"));
        assertEquals(new Day1P2.Result(55,3), Day1P2.process(55, "L300"));
    }

    @Test
    void test2P2() {
        Day1P2 day2 = new Day1P2("day1Test.txt");
        day2.run();
        assertEquals(6, day2.getCount0());
    }

    @Test
    void realP2() {
        Day1P2 day2 = new Day1P2("day1.txt");
        day2.run();
        assertEquals(6305, day2.getCount0());
    }
}
