/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day2Test {


    @Test
    void test() {
        //In the above example:
        //
        //    11-22 has two invalid IDs, 11 and 22.
        //    95-115 has one invalid ID, 99.
        //    998-1012 has one invalid ID, 1010.
        //    1188511880-1188511890 has one invalid ID, 1188511885.
        //    222220-222224 has one invalid ID, 222222.
        //    1698522-1698528 contains no invalid IDs.
        //    446443-446449 has one invalid ID, 446446.
        //    38593856-38593862 has one invalid ID, 38593859.
        //    The rest of the ranges contain no invalid IDs.
        check("11-22", 11, 22);
        check("95-115", 99);
        check("998-1012", 1010);
        check("1188511880-1188511890",1188511885);
        check("222220-222224",222222);
        check("1698522-1698528");
        check("446443-446449",446446);
        check("38593856-38593862",38593859);
    }

    private void check(String input, int... expected) {
        List<Long> res = Day2.process(input);
        assertEquals(expected.length, res.size());
        for (int i = 0; i < expected.length; i++) {
            assertEquals(expected[i], res.get(i));
        }
    }

    @Test
    void test2() {
        Day2 day2 = new Day2("day2Test.txt");
        day2.run();
        assertEquals(1227775554, day2.getCount());
    }

    @Test
    void real() {
        Day2 day2 = new Day2("day2.txt");
        day2.run();
        assertEquals(43952536386L, day2.getCount());
    }

    @Test
    void testP2() {
        checkP2("11-22", 11, 22);
        checkP2("95-115", 99,111);
        checkP2("998-1012", 999,1010);
        checkP2("1188511880-1188511890",1188511885);
        checkP2("222220-222224",222222);
        checkP2("1698522-1698528");
        checkP2("446443-446449",446446);
        checkP2("38593856-38593862",38593859);
        checkP2("565653-565659",565656);
        checkP2("824824821-824824827",824824824);
        checkP2("2121212118-2121212124",2121212121);
    }

    private void checkP2(String input, int... expected) {
        List<Long> res = Day2.processP2(input);
        assertEquals(expected.length, res.size());
        for (int i = 0; i < expected.length; i++) {
            assertEquals(expected[i], res.get(i));
        }
    }

    @Test
    void realP2() {
        Day2 day2 = new Day2("day2.txt");
        day2.runP2();
        assertEquals(54486209192L, day2.getCount());
    }
}
