/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day3Test {


    @Test
    void test() {
        // You'll need to find the largest possible joltage each bank can produce. In the above example:
        //    In 987654321111111, you can make the largest joltage possible, 98, by turning on the first two batteries.
        //    In 811111111111119, you can make the largest joltage possible by turning on the batteries labeled 8 and 9, producing 89 jolts.
        //    In 234234234234278, you can make 78 by turning on the last two batteries (marked 7 and 8).
        //    In 818181911112111, the largest joltage you can produce is 92.
        assertEquals(98, Day3.process("987654321111111"));
        assertEquals(89, Day3.process("811111111111119"));
        assertEquals(78, Day3.process("234234234234278"));
        assertEquals(92, Day3.process("818181911112111"));
    }


    @Test
    void test2() {
        Day3 day3 = new Day3("day3Test.txt", Day3::process);
        day3.run();
        assertEquals(357, day3.getCount());
    }

    @Test
    void real() {
        Day3 day3 = new Day3("day3.txt", Day3::process);
        day3.run();
        assertEquals(17524, day3.getCount());
    }

    @Test
    void testP2() {
        // You'll need to find the largest possible joltage each bank can produce. In the above example:
        //    In 987654321111111, you can make the largest joltage possible, 98, by turning on the first two batteries.
        //    In 811111111111119, you can make the largest joltage possible by turning on the batteries labeled 8 and 9, producing 89 jolts.
        //    In 234234234234278, you can make 78 by turning on the last two batteries (marked 7 and 8).
        //    In 818181911112111, the largest joltage you can produce is 92.
        assertEquals(987654321111L, Day3.processP2("987654321111111"));
        assertEquals(811111111119L, Day3.processP2("811111111111119"));
        assertEquals(434234234278L, Day3.processP2("234234234234278"));
        assertEquals(888911112111L, Day3.processP2("818181911112111"));
    }

    @Test
    void testP2v2() {
        Day3 day3 = new Day3("day3Test.txt", Day3::processP2);
        day3.run();
        assertEquals(3121910778619L, day3.getCount());
    }

    @Test
    void realP2() {
        Day3 day3 = new Day3("day3.txt", Day3::processP2);
        day3.run();
        assertEquals(173848577117276L, day3.getCount());
    }
}
