/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day4Test {


    @Test
    void test() {
        assertEquals(5, Day4.process(null, "..@@.@@@@.", "@@@.@.@.@@"));
        assertEquals(1, Day4.process("..@@.@@@@.", "@@@.@.@.@@", "@@@@@.@.@@"));
        assertEquals(3, Day4.process(".@@@@@@@@.", "@.@.@@@.@.", null));
    }

    @Test
    void test2() {
        Day4 day4 = new Day4("day4Test.txt");
        day4.runP1();
        assertEquals(13, day4.getCount());
    }

    @Test
    void testReal() {
        Day4 day4 = new Day4("day4.txt");
        day4.runP1();
        assertEquals(1424, day4.getCount());
    }

    @Test
    void testP2() {
        assertEquals(new Day4.Res(5, ".......@.."), Day4.processP2(null, "..@@.@@@@.", "@@@.@.@.@@"));
        assertEquals(new Day4.Res(1, ".@@.@.@.@@"), Day4.processP2("..@@.@@@@.", "@@@.@.@.@@", "@@@@@.@.@@"));
        assertEquals(new Day4.Res(3, "....@@@..."), Day4.processP2(".@@@@@@@@.", "@.@.@@@.@.", null));
    }

    @Test
    void test2P2() {
        Day4 day4 = new Day4("day4Test.txt");
        day4.runP2();
        assertEquals(43, day4.getCount());
    }

    @Test
    void testRealP2() {
        Day4 day4 = new Day4("day4.txt");
        day4.runP2();
        assertEquals(8727, day4.getCount());
    }


}
