/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventOfCode.app;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }

    public static void readLines(String filename, Consumer<String> lineConsumer) {
        try(InputStream is = Optional.ofNullable(MessageUtils.class.getResourceAsStream("/"+filename)).orElseThrow();
            BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
            while (true) {
                String line = br.readLine();
                if (line == null) {
                    return;
                }
                lineConsumer.accept(line);
            }

        } catch (IOException e) {
            throw new RuntimeException("error reading file " + filename, e);
        }
    }

    public static List<String> readLinesAll(String filename) {
        List<String> lines = new ArrayList<>();
        readLines(filename, lines::add);
        return  lines;
    }
}
